### ISSUE TITLE
Google的指定site的搜索问题

### ISSUE THREAD

**Issue by fandasoft** [cnodejs/nodeclub#1000]
目前的版本好像是采用的这种机制，一搜索就采用的google的site搜索。
论坛里面也有几个帖子是关于搜索的。

我这次构建的社区，其主要的对象基本都不会翻墙，因此想改变一下搜索方式，有什么推荐的办法？ 谢谢！

**Comment by tomoya92** [comment]
site:google.com -> site:baidu.com

**Comment by fandasoft** [comment]
谢谢热情的tomoya，请问在哪个文件改呢？ 配置文件里面好像没有。而且，baidu的site查找，是否只是对站点的首页有效？

**Comment by tomoya92** [comment]
@fandasoft 你在哪找到的Google.com 就在哪改呗，搜索是针对全站的

**Comment by fandasoft** [comment]
@tomoya92 谢谢，我找找。 我发现nodeclub使用google的site检索，是因为我输入关键字后进行检索，跳到了google的链接。比如：https://www.google.com.hk/#hl=zh-CN&q=site:cnodejs.org+测试

我再在源码中找找。多谢！

**Comment by fandasoft** [comment]
找到了，在下面这个文件里：nodeclub/controllers/search.js

内容：

`exports.index = function (req, res, next) {   `
`var q = req.query.q;   `
`q = encodeURIComponent(q);  `
`res.redirect('https://www.google.com.hk/#hl=zh-CN&q=site:cnodejs.org+' + q);   `
`};`
