### ISSUE TITLE
用户sucaihuo涉嫌盗版内容，暂时屏蔽

### ISSUE THREAD

**Issue by i5ting** [cnodejs/nodeclub#1002]
https://cnodejs.org/user/sucaihuo

入门到精通nodejs视频教程，要学的可以看看 http://www.sucaihuo.com/video/135.html

**Comment by tomoya92** [comment]
这种不应该发在cnodejs.org上吗？加个置顶什么的，怎么放到issues里了

**Comment by alsotang** [comment]
哈哈，发到issue确实能被更多管理员看到。

这个用户的id跟课程的网址基本一样，看来是网址的所有人举报了这个id的感觉。

**Comment by i5ting** [comment]
我把这个问题close了，加了一个标签叫屏蔽用户
