### ISSUE TITLE
我想在 请求头部里添加 X-Frame-Options在哪里？

### ISSUE THREAD

**Issue by pangguoming** [cnodejs/nodeclub#1027]
用iframe嵌入 您的项目网页显示为空白，并报错：
Refused to display 'http://********/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
哪里可以修改X-Frame-Options头部？ 我没有找到，请指点
java中是这样的response.setHeader("X-Frame-Options", "SAMEORIGIN");// 解决IFrame拒绝的问题

**Comment by oodzchen** [comment]
https://github.com/cnodejs/nodeclub/blob/master/app.js#L89
