### ISSUE TITLE
同一服务器，同一MongoDB下部署 两套 nodeclub 在不同域名下，数据串了

### ISSUE THREAD

**Issue by pangguoming** [cnodejs/nodeclub#1071]
同一服务器，同一MongoDB下（各自数据库名不同）部署 两套 nodeclub 在不同域名下，数据串了
打开新部署的nodeclub 主页， 右侧 无人回复话题 与 积分榜 居然有 同服务器下另一个nodeclub的数据。
刷新后 有时 积分榜 又显示正常，可能是前端原因

![image](https://user-images.githubusercontent.com/7269202/54907143-c9384780-4f1f-11e9-9a30-fc7c8ad8f9be.png)

**Comment by alsotang** [comment]
如果数据库名不同，nodeclub不可能自己猜测出对应的名字来，是否你在两套nodeclub配置混了东西？
也可能是因为他们共用同一个redis导致一些缓存数据混了。（这个可能性需要排查）

**Comment by pangguoming** [comment]
redis的可能性挺大的

**Comment by tomoya92** [comment]
@alsotang 可以考虑给nodeclub上用的redis缓存设置一个有效期，时间短点，过时了，缓存数据自然就没有了

**Comment by alsotang** [comment]
@tomoya92 现在是混用的问题，不是缓存过期的问题。你设得再短还是不能混用啊。

**Comment by alsotang** [comment]
@tomoya92 而且缓存数据过期了也是面临重新生成，不是什么自然没有了

**Comment by tomoya92** [comment]
@alsotang 我说的是这个TTL，默认是 -1，永不过期，设置上过期时间后，redis里就没有了

不过混用也可以考虑给缓存到redis里的数据的key加个前缀，比如 redis.set('nodeclub_xxx', value);

![image](https://user-images.githubusercontent.com/6915570/55053404-0410bb80-5097-11e9-8528-2a9204e88f4b.png)

**Comment by alsotang** [comment]
https://github.com/cnodejs/nodeclub/blob/cac37e53e7930d235c38ec6f8e68d0b88fc2f19e/config.default.js#L43 通过这个参数来使用不用redis db即可。或者不同的redis实例。

redis ttl 跟这个issue没关系。

**Comment by pangguoming** [comment]
明白

**Comment by pangguoming** [comment]
![image](https://user-images.githubusercontent.com/7269202/55138466-81f3c600-516e-11e9-9c1f-b079fd335c8e.png)
奇怪，我本地已经是这样配置了，也就是说我根本没用redis， 也就是~~~不是Redis的原因
