### ISSUE TITLE
同一服务器，同一Redis下部署 两套 nodeclub 在不同域名下，右侧 无人回复的话题、积分榜  数据串了

### ISSUE THREAD

**Issue by pangguoming** [cnodejs/nodeclub#1077]
如题，我在同一服务器下部署了两个cnode 项目 开了两个论坛
结果 右侧栏目 里的数据都串了
网址如下：
http://servicemesh.dev/
http://neo4j.com.cn/
求解决方案

**Comment by alsotang** [comment]
https://github.com/cnodejs/nodeclub/blob/3fd1fcc8a739ed6289fee75e898cea0ca177bb8c/config.default.js#L43

一个用0，一个用1试试

**Comment by pangguoming** [comment]
收到 已经 在cnode中文社区 得到答案，谢谢
