### ISSUE TITLE
论坛 RSS 报XML 错误

### ISSUE THREAD

**Issue by shenqidebaozi** [cnodejs/nodeclub#1084]
https://cnodejs.org/rss
This XML file does not appear to have any style information associated with it. The document tree is shown below.、
页面没渲染
![image](https://user-images.githubusercontent.com/35397691/62668105-2c051980-b9bd-11e9-9a51-45a9846d8bb7.png)

**Comment by alsotang** [comment]
rss结果不带样式很正常啊，影响哪方面的使用吗？

**Comment by shenqidebaozi** [comment]
(╯▽╰)只是看着怪怪的

**Comment by alsotang** [comment]
你搜一下这个提示看看，感觉是很正常的一个提示

**Comment by shenqidebaozi** [comment]
我知道，就是没关联样式。只是感觉没样式不好看，233333.

**Comment by awong1900** [comment]
rss 用于数据交换，没有样式正常的。
