### ISSUE TITLE
易用性与可扩展性改善计划

### ISSUE THREAD

**Issue by leizongmin** [cnodejs/nodeclub#404]
## 1、使用方式

现在的使用方式是：
- 1、克隆代码：`git clone https://github.com/cnodejs/nodeclub.git`
- 2、安装依赖模块：`npm install`
- 3、创建配置文件：`cp config.js.default config.js`
- 4、启动：`node app`

如果仅仅作为cnodejs.org网站来运行，这样似乎是没啥问题的，而当把nodeclub定位为一个通用的论坛程序，让更多的人通过nodeclub来搭建自己的网站，这种方式就显得不那么友好。以下是我设计的使用方式：

1、创建文件`app.js`

``` JavaScript
// nodeclub作为一个模块发布
var server = require('nodeclub');
// 载入配置
server.config(require('./config'));
// 启动服务
server.start();
```

2、启动：`node app`

这种方式的好处有：
- 1、通过NPM来安装并使用，更符合Node.js应用的惯例，同时也不需要额外依赖Git来安装
- 2、通过版本号来确定使用那个nodeclub版本
- 3、方便核心代码与模板分离（见下文）
## 2、核心代码与模板分离

目前nodeclub的核心代码和模板都是都放在一起，假如用户使用nodeclub来搭建一个网站，并修改了模板，当nodeclub代码更新后（比如修复了某些bug），用户要应用这些更新就显得没那么容易，可能需要一下操作：
- 1、下载最新的代码：`git clone https://github.com/cnodejs/nodeclub.git`
- 2、将自己修改的`public`和`views`目录覆盖到新的nodeclub代码目录

假如核心代码和模板分离，那用户要升级nodeclub就显得方便得多：

``` JavaScript
// nodeclub作为一个模块发布
var server = require('nodeclub');
// 载入配置
server.config(require('./config'));
// 自定义主题./custom_theme_dir目录包含修改过的public和views目录的文件
server.theme('./custom_theme_dir');
// 启动服务
server.start();
```

当要升级nodeclub时，只需安装新版本的模块即可，甚至不需要改动任何代码：`npm install nodeclub@latest`
## 3、组件化

当完成以上两部分的改进后，甚至可将nodeclub一些扩展功能打包成模块，用户要使用时只需通过NPM安装相关模块，然后在代码中载入即可，比如要将编辑器换成UEditor：

1、安装模块：`npm install nodeclub-ueditor`
2、在`app.js`中载入：`server.use('nodeclub-editor');`

---

以上是我的一些想法，不知道大家怎么看？

**Comment by alsotang** [comment]
后来再看，还是一种抽象过度。

大家现在看呢？

**Comment by xiaokekeT** [comment]
不太支持，不是太有必要

**Comment by fengmk2** [comment]
可以参考这种做法 https://github.com/cnpm/npm.taobao.org
