### ISSUE TITLE
要不要考虑换一个markdown解析库

### ISSUE THREAD

**Issue by albertshaw** [cnodejs/nodeclub#440]
之前报了一个marked的xss问题，https://github.com/chjj/marked/issues/492, 不过因为是特定浏览器下的反射型xss，所以我自己也没太在意(在cnodejs也[提过](https://cnodejs.org/topic/5056695398ee0904200b79ec#reply84)，估计你们也不在意这个)，隔了这么久才想起来看他们解决了没，却发现仍然是open的。

然后发现这个issue被https://github.com/julianlam/nodebb-plugin-markdown/issues/20 引用了，顺着过去看才发现marked问题不少，导致nodebb的markdown插件换了个解析库https://github.com/jonschlinkert/remarkable。

其中一个问题https://github.com/chjj/marked/issues/497 还蛮严重的，导致nodebb直接无响应了 https://github.com/akhoury/nodebb-plugin-import/issues/61。

**Comment by fengmk2** [comment]
也会出现性能问题 remarkable

https://github.com/cnpm/cnpmjs.org/issues/552

我现在能随意将 cnode 弄挂，请尽快切换到 markdown-it

**Comment by fengmk2** [comment]
https://github.com/jgm/CommonMark/issues/263

**Comment by fengmk2** [comment]
html: false https://github.com/cnodejs/nodeclub/blob/master/common/render_helper.js#L23 没有开启 html，那么就没问题了。。。

**Comment by alsotang** [comment]
好的好的，晕呐。

**Comment by alsotang** [comment]
当时之所以禁止 html 也是因为开启了 html 之后，xss 的风险太大，我无法信任 markdown 的库可以把各种 xss 陷阱都绕过。而且就目前的情况来看，只用 markdown 语法大家也能顺畅交流，就直接关闭了。

**Comment by fengmk2** [comment]
@alsotang 嗯，将 html 关闭吧。

**Comment by fengmk2** [comment]
@alsotang 另外一种选择，开启 html，然后再加一层 js-xss 过滤 https://github.com/leizongmin/js-xss

**Comment by alsotang** [comment]
我当时特意去掉了 js-xss 这个库。我看了他的实现，里面各种正则，也还是属于黑名单的机制。一年前我还绕过了一次：https://cnodejs.org/topic/52b827e9588ff25a72ce204a <https://cnodejs.org/topic/52b827e9588ff25a72ce204a>

还是不开启 html 了。

**Comment by fengmk2** [comment]
ping @leizongmin

**Comment by fengmk2** [comment]
总得与时俱进啊，老雷也会不断修复 bug 的  

--  
fengmk2
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by alsotang** [comment]
肯定得与时俱进，不过开启 html 的必要性不强吧？

**Comment by leizongmin** [comment]
js-xss是基于白名单过滤的，但是实现过程中总会有点Bug，__使用过程中若发现安全问题我会马上修复，不过这需要大家共同参与，提issue__。我希望js-xss模块是由大家共同完善的。

**Comment by fengmk2** [comment]
现在完全过滤html，导致一些3年前比较好的文章完全无法看了

**Comment by leizongmin** [comment]
我个人意见是需要开放部分HTML标签，只支持Markdown显得太保守。总不能因为遇到一点问题就一刀切去掉HTML支持。

**Comment by fengmk2** [comment]
重新 reopen，开放讨论

**Comment by fengmk2** [comment]
如 https://cnodejs.org/topic/4f16442ccae1f4aa270010ab

**Comment by alsotang** [comment]
有历史遗留问题是肯定的，当然这也导致了原来很多隐藏的 xss 都失效了

**Comment by alsotang** [comment]
上到 github，下到百度贴吧，谁敢支持用户回复 html

**Comment by albertshaw** [comment]
白名单支持是可以的吧，markdown其实就是相当于变相白名单嘛。

**Comment by fengmk2** [comment]
github支持html的。
百度，为什么要学百度，百度md都不支持

**Comment by alsotang** [comment]
失误失误，github 确实是支持 html 的：https://github.com/github/markup/tree/master#html-sanitization <https://github.com/github/markup/tree/master#html-sanitization>
> 在 2015年1月6日，21:03，fengmk2 <notifications@github.com> 写道：
> 
> github支持html的。 
> 百度，为什么要学百度，百度md都不支持 
> 
> Sent from my iPhone 
>

**Comment by alsotang** [comment]
@fengmk2 https://cnodejs.org/topic/4f16442ccae1f4aa270010ab 老的帖子已经可以看了，还在微调样式中
