### ISSUE TITLE
发布的时候出现500 status错误

### ISSUE THREAD

**Issue by nosqldb** [cnodejs/nodeclub#448]
500 status

可能是内容有点大？utf8保存大概50k的样子

**Comment by wanghaisheng** [comment]
同样的问题我也遇到了 新建话题时提交的内容过大，根据上面的回复
我在app.js里添加了
app.use(bodyParser.urlencoded({limit: '50mb'}));
但是仍然是500的错误

**Comment by alsotang** [comment]
把 bodyparser.urlencoded 移到 bodyparser.json 的上面试试

**Comment by wanghaisheng** [comment]
answer to body-parser parsing too large contents
```
var bodyParser = require('body-parser');
app.use(bodyParser.json({limit: '50mb'}));
app.use(bodyParser.urlencoded({limit: '50mb', extended: true}));
```
[reference](http://stackoverflow.com/questions/19917401/node-js-express-request-entity-too-large)
