### ISSUE TITLE
markdown 渲染时的 html 支持

### ISSUE THREAD

**Issue by alsotang** [cnodejs/nodeclub#468]
@fengmk2 @leizongmin 

我周末的时候加一下这部分代码

**Comment by alsotang** [comment]
markdown 的渲染库换成 markdown-it https://github.com/markdown-it/markdown-it

**Comment by fengmk2** [comment]
good

**Comment by alsotang** [comment]
closed by https://github.com/cnodejs/nodeclub/commit/3587bcabb1e7137153cca39886d16f18f4ae6b22
