### ISSUE TITLE
使用 Github 登入的帳號與舊帳號不同步

### ISSUE THREAD

**Issue by chinghanho** [cnodejs/nodeclub#472]
首頁上看到的是這樣：

![screen shot 2015-01-16 at 2 21 54 pm](https://cloud.githubusercontent.com/assets/1897143/5772291/0f1dac9a-9d8b-11e4-881b-9fe363c69bee.png)

點進去後變這樣：

![screen shot 2015-01-16 at 2 22 44 pm](https://cloud.githubusercontent.com/assets/1897143/5772295/31b8cd98-9d8b-11e4-9951-f9f2e0038377.png)

且最近參與的話題也只有舊的。 :confused:

**Comment by alsotang** [comment]
可能当时上新账号系统的时候发生了一点冲突，我去看看

**Comment by alsotang** [comment]
修复了一下，你看看

**Comment by chinghanho** [comment]
OK 了，謝謝！:D
