### ISSUE TITLE
fork之后的github登录配置

### ISSUE THREAD

**Issue by wanghaisheng** [cnodejs/nodeclub#476]
您好，
我fork了一份代码，如果想在本地使用github的功能，是否修改config.js文件中的如下代码即可
```
  // github 登陆的配置
  GITHUB_OAUTH: {
    clientID: 'wanghaisheng',
    clientSecret: 'your GITHUB_CLIENT_SECRET',
    callbackURL: 'http://localhost:3000/auth/github/callback'
  },
```
但问题来了，这里的clientSecret是怎么得到的呢
callbackURL是否就是Developer applications-Register a new OAuth application -Authorization callback URL 这里是否必须是公网的域名

**Comment by alsotang** [comment]
去 github 申请 client secret
url 不必是公网的

**Comment by wanghaisheng** [comment]
thx
