### ISSUE TITLE
回复的显示体验不好

### ISSUE THREAD

**Issue by feitian124** [cnodejs/nodeclub#479]
如下图所示, 头像显示在前面, 用户名和时间显示在后面, 看到头像还不能确定回复者是谁, 要转一下眼珠到末尾看下用户名和回复时间, 我觉得体验不怎么好. 至少用户名和头像放在一起.
![](http://ming.qiniudn.com/reply.png)

 像 https://ruby-china.org/topics/23892 那样的回复样式怎么样?

**Comment by microlv** [comment]
感觉应该使用开放的评论系统,省时省力.
如disqus

**Comment by alsotang** [comment]
.................
@andy 当自定义 feature 多的时候，用那些东西反而麻烦。disqus 对于 markdown 预览，js 语法高亮什么的。hack 它很麻烦的。

**Comment by feitian124** [comment]
@alsotang 你 At 了谁? andy是一个 Moscow, Evil Russia 的哥们, 也不是这个项目的贡献者亚...
言归正传, 需要的话我我可以提交一个 pull request, 最近正研究 cnodejs 代码~

**Comment by alsotang** [comment]
@feitian124 不好意思，在 github 的邮件中， @microlv 显示为 andy.lv 。
pr 的话，样式好看点就好啦。你提的这个 issue 欢迎有 pr 一起来：）
