### ISSUE TITLE
通过github关联已注册账号导致用户名被修改

### ISSUE THREAD

**Issue by lanceli** [cnodejs/nodeclub#482]
当时注册的用户名为ilanceli， 话说lanceli已被注册

当关联自己github @lanceli 后，自己的用户名被修改成lanceli。

**Comment by alsotang** [comment]
我订正了一下数据，你的用户名回到 ilanceli 了。
以及，之前有个用户跟我说希望 cnode 用户名随 github 变更我才加的逻辑。现在我把用户名变更的逻辑去掉了，以后用户名一旦注册不可更改。

你看 ok 了没？

**Comment by lanceli** [comment]
我的账号已恢复正常

恩 不可更改的好
