### ISSUE TITLE
cannot find module './config' solution

### ISSUE THREAD

**Issue by Matrixbirds** [cnodejs/nodeclub#495]
the error info :
module.js:340
         throw err;
Error: Cannot find module './config'

![stepone](https://cloud.githubusercontent.com/assets/9990676/6478363/77eeac14-c26c-11e4-9b46-3cfb400eb7bb.jpg)

Because the default module file named config.default.js so you should rename or add the config.js file
in this project
For example: you can just copy config.default.js to config.js that is very simple and you can run this demo easily
![steptwo](https://cloud.githubusercontent.com/assets/9990676/6478364/79969716-c26c-11e4-878c-8039d698fd23.jpg)
![stepthree](https://cloud.githubusercontent.com/assets/9990676/6478365/7b78673a-c26c-11e4-8cc0-cf9b26efd65c.jpg)

**Comment by JacksonTian** [comment]
之前readme里有提到`cp config.default.js config.js`的操作。谁删了？@alsotang

**Comment by alsotang** [comment]
fixed by #497
