### ISSUE TITLE
编辑器样式问题

### ISSUE THREAD

**Issue by DongHongfei** [cnodejs/nodeclub#496]
![833b3419-d996-4ef0-a279-dd8bdeee8034](https://cloud.githubusercontent.com/assets/5700428/6507073/8c8bba44-c38a-11e4-8124-ea803253359e.png)

解决方案：
增加样式 .CodeMirror-sizer{min-width:100px!important}

**Comment by alsotang** [comment]
merged by  #497

**Comment by alsotang** [comment]
thx
