### ISSUE TITLE
CNode 改进计划 2015-04

### ISSUE THREAD

**Issue by alsotang** [cnodejs/nodeclub#503]
1. 去掉 nginx 的 ratelimit 限制
2. nodejs 层面 ratelimit 加入
3. avatar 代理
4. 缓存用上 redis
  包括 common/cache.js 和 session
  更新对应的 readme 和 config.js
5. 删除改为软删除
6. 研究数据库备份策略
7. 加快 moogodb 的查询速度

**Comment by luoyjx** [comment]
要不要研究朴神说的垃圾检测，哈哈~

**Comment by luoyjx** [comment]
上次想了一下策略，可能很逗比~
- 这个值初始1
- 在每次发帖的时候 * 2
- 达到2的10（或20）次方的时候暂时锁定用户（忘记nodeclub锁定用户的帖子能不能显示了），再积极的小伙伴好像一天也发不了10（或20）个高质量帖子
- 定时任务每天将这个值除以2的4次方，小于4的就不除

也没有仔细想~

**Comment by alsotang** [comment]
我打算直接限制每天只能发三个贴

在 2015年4月3日 上午8:12，yanjixiong <notifications@github.com>写道：

**Comment by luoyjx** [comment]
隐约觉得稍感束缚。
恩，不过可以先试行，看效果如何。

**Comment by jysperm** [comment]
提供一个方案，可以为每个用户统计「活跃天数」这个指标，即总共有多少天发过帖子。不考虑性能的话，直接查这个用户的所有帖子，按日期分组，分组的数量就是活跃天数。

然后限制用户每天的发帖数量最多为他的活跃天数（再加上一）。如果是新用户的话第一天只能发一个帖子，第二天可以发两个，以此类推，如果是老用户的，接近于无限制。另外除了发帖限制，这也是一个很不错的用来量化用户活跃度的指标。

**Comment by foolmath** [comment]
Cookie 里只保存 user_id 是不是不安全
