### ISSUE TITLE
autherror 和 ratelimit forbidden

### ISSUE THREAD

**Issue by wanghaisheng** [cnodejs/nodeclub#507]
更新到最近版本后   注册新的用户提示如下错误

{ [AuthError: Invalid login - 550 �û���Ȩ��½] name: 'AuthError', data: '550 �û���Ȩ��½', stage: 'auth' }

  // 邮箱配置
  mail_opts: {
    host: 'smtp.126.com',
    port: 25,
    auth: {
      user: 'club@126.com',
      pass: 'club'
    }
  },
中的用户名和密码在126的网页中是可以登录的

**Comment by wanghaisheng** [comment]
被126的文档骗了
新建的账号还是要手动在设置里开启SMTP的选项

**Comment by wanghaisheng** [comment]
// 邮箱配置
  mail_opts: {
    host: 'smtp.126.com',
    port: 25,
   auth: {
      user: 'wondersinformatic@126.com',
      pass: 'clubclub'
    }
  },

  // 邮箱配置
  mail_opts: {
    host: 'smtp.126.com',
    port: 465,
    secure: true,
	auth: {
      user: 'wondersinformatic@126.com',
      pass: 'clubclub'
    },
	debug: true,
    tls: {
        rejectUnauthorized: false // allow invalid certificates
    }	
  },
按照这两种设置调试了一下nodemailer 仍然是报错的 ，提示如下
```
^C%                                                                             ➜ /Users/wanghaisheng/workspace/wondersinformaticsclub git:(master) ✗>node app.js
NodeClub listening on port 3000
God bless love....
You can debug your app with http://localhost:3000
SERVER 1:
└──220 126.com Anti-spam GT for Coremail System (126com[20140526])
CLIENT 1:
└──EHLO wanghaishengdeMacBook-Pro.local
SERVER 1:
└──250-mail
   250-PIPELINING
   250-AUTH LOGIN PLAIN
   250-AUTH=LOGIN PLAIN
   250-coremail 1Uxr2xKj7kG0xkI17xGrU7I0s8FY2U3Uj8Cz28x1UUUUU7Ic2I0Y2UroXZ8pUCa0xDrUUUUj
   250-STARTTLS
   250 8BITMIME
CLIENT 1:
└──STARTTLS
SERVER 1:
└──220 Ready to start TLS
Connection secured
CLIENT 1:
└──EHLO wanghaishengdeMacBook-Pro.local
SERVER 1:
└──250-mail
   250-PIPELINING
   250-AUTH LOGIN PLAIN
   250-AUTH=LOGIN PLAIN
   250-coremail 1Uxr2xKj7kG0xkI17xGrU7I0s8FY2U3Uj8Cz28x1UUUUU7Ic2I0Y2UFf21euUCa0xDrUUUUj
   250-STARTTLS
   250 8BITMIME
CLIENT 1:
└──AUTH PLAIN AHdvbmRlcnNpbmZvcm1hdGljQDEyNi5jb20AY2x1YmNsdWI=
SERVER 1:
└──535 Error: authentication failed
{ [AuthError: Invalid login - 535 Error: authentication failed]
  name: 'AuthError',
  data: '535 Error: authentication failed',
  stage: 'auth' }
Closing connection to the server
```

**Comment by wanghaisheng** [comment]
github授权的账号是可以登录的，但发布话题，提交之后会报
ratelimit forbidden

**Comment by wanghaisheng** [comment]
参考这里https://cnodejs.org/topic/543c756f91eadb0f73aa33f4
认证错误应该是公司内部做了限制 不知道还有没有其他办法

**Comment by alsotang** [comment]
新版本加了 ratelimit，对照一下你现在使用的 config.js 与 github 仓库里面的 config.default.js
，是不是少了下面三个字段

  create_post_per_day: 1000, // 每个用户一天可以发的主题数
  create_reply_per_day: 1000, // 每个用户一天可以发的评论数
  visit_per_day: 1000, // 每个 ip 每天能访问的次数

在 2015年4月7日 下午4:07，wanghaisheng <notifications@github.com>写道：

**Comment by wanghaisheng** [comment]
果然。。。fix
这个auth error有没有办法呢

**Comment by toby20130333** [comment]
有人遇到过吗 我之前126邮箱发送激活邮件妥妥的，最近发送老是失败，用户都说收不到激活邮件

**Comment by alsotang** [comment]
126 对于发送邮件的限制吧

在 2015年6月2日 下午3:08，一衣带水 <notifications@github.com>写道：

**Comment by toby20130333** [comment]
那就没有办法解决吗？换成企业邮箱能否解决这个问题呢
