### ISSUE TITLE
回复删除后主题的最后回复时间和最后回复人

### ISSUE THREAD

**Issue by jinceon** [cnodejs/nodeclub#511]
假设某主题有7个回复。
这时用户A去提交第8个回复。提交成功后，最后回复人显示为A。
用户A随即就删除刚刚发表的回复。删除成功后，最后回复人依然显示为A。

最后回复时间同理。

**Comment by alsotang** [comment]
这个地方确实可以在删除回复之后去更新一下对应的帖子

在 2015年4月14日 上午9:32，JinCeon <notifications@github.com>写道：

**Comment by alsotang** [comment]
这个地方倒是环境 pull request 哈

在 2015年4月14日 上午11:00，alsotang <alsotang@gmail.com>写道：

**Comment by jinceon** [comment]
4月14.。。。。呃

**Comment by alsotang** [comment]
@jinceon 这个已经修了

**Comment by jinceon** [comment]
嗯嗯，所以我已经closed掉了
