### ISSUE TITLE
编辑回复时，新增的@用户

### ISSUE THREAD

**Issue by jinceon** [cnodejs/nodeclub#512]
假设第一次回复时，@张三 @李四 @王五，会发消息通知这3人。
提交成功后，修改该回复，同时新增加@孙六。
系统并未增量通知@孙六。

是否会考虑修改？其实我也感觉这是好无聊的问题，真要@谁的话再发一条评论就好啦，哈哈
如果会考虑修改，但是你们忙的话，其实我周末也可以试试提交pr，哈哈

**Comment by alsotang** [comment]
不改了吧，保持简单。

在 2015年4月14日 上午9:36，JinCeon <notifications@github.com>写道：
