### ISSUE TITLE
线上部署注册邮件问题

### ISSUE THREAD

**Issue by wikieswan** [cnodejs/nodeclub#524]
问题：

我fork了一份代码，本地部署了一份代码，跑起来都没问题，注册邮件也是可以收到。

但是线上的代码就无法收到注册邮件，请问怎么解决？

贴出我的config.js

```javascript
var config = {
  // debug 为 true 时，用于本地调试
  debug: false,
  .....
   // 邮箱配置
  mail_opts: {
    host: 'smtp.126.com',
    port: 25,
    auth: {
      user: 'knockoutjscn@126.com',
      pass: 'password'
    }
  },
}
```

**Comment by alsotang** [comment]
线下都行的话，那配置应该是没问题的

在 2015年5月7日 下午4:02，wikieswan <notifications@github.com>写道：

**Comment by wikieswan** [comment]
@alsotang  恩，config.js配置没问题的，这种情况可能是主机问题吗？能给个解决的思路吗？

**Comment by alsotang** [comment]
把本地的config.js原封不动放上去还不行的话，说不定是主机的问题。

在 2015年5月7日 下午8:43，wikieswan <notifications@github.com>写道：

**Comment by alsotang** [comment]
用的是哪里的主机？

在 2015年5月8日 下午7:31，alsotang <alsotang@gmail.com>写道：

**Comment by wikieswan** [comment]
可能是主机的问题吧，用的香港的vps，现在正在联系主机服务方，正在查找问题！等有结果马上回复

**Comment by wikieswan** [comment]
是邮箱设置问题，现在才想起来关闭issue，sorry！谢谢@alsotang的帮助。
