### ISSUE TITLE
UPYUN Open Talk 永不止步：移动应用架构的重塑与优化

### ISSUE THREAD

**Issue by y411040724** [cnodejs/nodeclub#543]
# UPYUN Open Talk 永不止步：移动应用架构的重塑与优化 #

![](http://lock522.b0.upaiyun.com/11.jpg)

面对各自产品的独特挑战，架构师们的作用举足轻重。他们擅用相对简单的底层服务，和敏捷开发实践，完成极度复杂高效的架构。

UPYUN Open Talk 第十一期《永不止步：移动应用架构的重塑与优化》再次抵达上海，邀请到“in”安卓负责人冯明、“扇贝”产品与技术负责人吴焱红、“饿了么”移动端负责人胡彪，分享移动应用背后的架构演进之路。

## 活动时间 ##

2015 年 7 月 25  日  13:00 - 17:30

## 活动地址 ##

上海 · 徐汇，古美路 1582 号总部园 2 期 C 幢  2 F

## 报名链接 ##

[http://www.huodongxing.com/go/upyun-open-talk-no11](http://www.huodongxing.com/go/upyun-open-talk-no11)

## 活动流程 ##

13:00-14:00　　签　到

14:00-14:20　　开　场

14:20-15:10　　分享一　　　冯　明　　in 安卓负责人　　《敏捷移动开发实践》

15:10-16:00　　分享二　　　吴焱红　　扇贝 产品和技术负责人　《扇贝使用 Aerospike 成功破解 VPS 性能下降》

16:00-16:20　　茶　歇

16:20-17:10　　分享三　　　胡　彪　　饿了么 移动端负责人　《饿了么？——解决千万人吃饭问题的移动架构》

17:10-17:30　　交　流

## 嘉宾简介 ##
![](http://lock522.b0.upaiyun.com/%E4%BC%A03.jpg)

**冯明　　in 安卓负责人**

专注于移动开发多年，擅长 Android 开发、Android 系统框架与原理，在移动开发领域有丰富的经验。

**分享主题　《敏捷移动开发实践》**

在敏捷开发的同时，面对不断变化的需求、挑战与问题，九言探索了合适自己的移动开发模式，采用了新的架构来应对移动端开发的压力。

![](http://lock522.b0.upaiyun.com/%E4%BC%A01.jpg)

**吴焱红　扇贝产品和技术负责人**

扇贝共同创始人， 一直热衷在社区分享。

**分享主题　《扇贝使用 Aerospike 成功破解 VPS 性能下降》**

扇贝在从南京机房整体迁移上云后，由于云上机器性能下降以及价格数倍上升，我们曾经两次更换 Cache 。最早从 redis 迁移到 codis，然后再次从 codis 迁移大部分数据到 aerospike， 解决了缓存压力的同时，也解决了codis 需要人工干预分片的问题，使得公司在缓存方面的直接成本下降至原来 1/3 左右， 也大大减轻了运维人员的压力。

![](http://lock522.b0.upaiyun.com/%E4%BC%A02.jpg)

**胡彪　饿了么商户移动端负责人**

09 年投身移动互联网研发。现饿了么 Napos 移动端负责人。曾先后任职于新蛋、盛大、百度、腾讯等国内外知名企业，先后参与 HotelVP、UUCUN 创业公司。 

**分享主题　《饿了么？——解决千万人吃饭问题的移动架构》** 

随着移动项目业务越来越复杂，功能越来越多一个耦合性低、扩展性强的项目结构就显的尤为重要，饿了么经过多年积累，饿了么逐渐形成了一个高稳定，低耦合，高内聚，高扩展的移动系统架构。本次主要分享饿了么移动架构演变之路，深入剖析前后台解耦方式。

## 讲稿 / 视频回顾 ##

[http://opentalk.upyun.com](http://opentalk.upyun.com)

## 主办方 ##

____________________________

UPYUN Open Talk 是由 UPYUN 发起的系列主题分享沙龙。秉承 UPYUN 帮助企业提升发展速度的初衷，UPYUN Open Talk 将用全干货的形态，为互联网从业人员呈现以技术为主，同时涵盖产品、营销、融资等各个方面的专业知识，帮助企业成员不断的提升自身专业技能，以推动企业更快的发展。

**报名链接**
[http://www.huodongxing.com/go/upyun-open-talk-no11](http://www.huodongxing.com/go/upyun-open-talk-no11)

**Comment by JacksonTian** [comment]
发在这里是神马意思？
