### ISSUE TITLE
api消息接口：get /messages 获取已读和未读消息 是返回用户创建开始所有的消息吗

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#552]
这个返回的是所有的消息吗，还是会返回最近xx条消息？
目前没收到太多消息，没测到上限

**Comment by alsotang** [comment]
已读是最近几十条，具体20还是30忘了。
未读是所有未读。
未读那个接口，访问的时候，就会全部标记为已读。
所以取 count 的话，有专门的 count 接口。

在 2015年8月7日 下午10:08，幻影狼人 <notifications@github.com>写道：
