### ISSUE TITLE
api接口中关于 avatar_url 这个参数

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#554]
我看到commit中有提到取消通过代理的方式获取avatar

目前线上接口获取的avatar_url是直接地址
而之前获取的格式是  agent/{url}，客户端调用的时候是手动拼接的：`https://cnodejs.org + /agent/{url}`

以后返回的avatar_url规定为不使用代理而是直接地址了吗？

**Comment by TakWolf** [comment]
最好可以都返回直接地址，即使以后又恢复成代理模式，api也返回代理后的完整地址

这样调用端就不需要重新打包发布了

**Comment by TakWolf** [comment]
和这个相同的还有两个情况，分别是用户@协议和web端上传图片的url地址协议，目前客户端进行了过滤处理

![image](https://cloud.githubusercontent.com/assets/6064962/9215989/152da8d0-40e5-11e5-93b4-09773d43c9ea.png)

这两个协议长远来看是不是也是不可靠的

**Comment by alsotang** [comment]
1. 这个 `avatar_url` 的地方，以后我都返回直接地址。
2. 下面提到的两个协议，长远来看是可靠的。

**Comment by TakWolf** [comment]
OK, get!

**Comment by alsotang** [comment]
这个地方是我的设计失误，现在我已经将这块代理逻辑从 model 中迁移至 view 中了。

2015-08-12 11:58 GMT+08:00 TakWolf <notifications@github.com>:
