### ISSUE TITLE
用户的accessToken有效期是多少

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#555]
例如，用户不小心泄露的accessToken，希望通过例如修改密码的行为，让当前的accessToken失效，让服务器产生新的accessToken

目前的策略是什么？

**Comment by alsotang** [comment]
目前并没有这方面的策略。。。。

要做的话，可以加个重新生成 accesstoken 的逻辑和按钮进去。

在 2015年8月12日 下午6:43，TakWolf <notifications@github.com>写道：

**Comment by TakWolf** [comment]
http://cnode-api.takwolf.com

https://github.com/TakWolf/CNode-Image-Upload-API

已经部署这个服务来解决图片上传的问题

希望可以添加这个功能让用户随时选择让token失效
