### ISSUE TITLE
API接口，get /messages 获取已读和未读消息  这个接口中，没有mdrender参数

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#564]
get /messages 这个接口中返回的对象中，有一个reply对象，其中的content字段为 markdown格式

这个接口中没有给 mdrender 参数来进行预渲染

**Comment by alsotang** [comment]
https://github.com/cnodejs/nodeclub/commit/3e084dc3a0fd48d1457f7eae101a911400923343

已经加上了，你看看好了没？

话说你微信是什么？我这里搜不到你。我们加一个吧，我号码是：alsotang

**Comment by TakWolf** [comment]
动作好快啊！！

**Comment by TakWolf** [comment]
我的微信是  TakWolf [幻影狼人]

我搜了一下你的，感觉不像啊...
