### ISSUE TITLE
用户头像一致性的问题

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#565]
用户发的帖子：

https://cnodejs.org/topic/562662ab1af271c54823a77e

![image](https://cloud.githubusercontent.com/assets/6064962/10630445/2545b00e-7809-11e5-8fbc-913ba6be3f32.png)

而在用户页面查看的时候，头像变化了：

https://cnodejs.org/user/pd0395

![image](https://cloud.githubusercontent.com/assets/6064962/10630470/3ae66c0a-7809-11e5-8524-4e415a8f8d65.png)

网站和API接口都有这个问题

**Comment by luoyjx** [comment]
这个问题我也有发现过，不过感觉像是github那边cdn节点的问题

**Comment by TakWolf** [comment]
这俩用户积分数目不一样，不清楚是不是同一个用户

另外，我在网站首页显示的积分

![image](https://cloud.githubusercontent.com/assets/6064962/10630536/c4b71da8-7809-11e5-81ab-1bc2aeb0cf29.png)

和我在个人页面的积分

![image](https://cloud.githubusercontent.com/assets/6064962/10630546/d035596a-7809-11e5-9a0f-3974743f2247.png)

数目也是不一致的

我看到很多请求的返回状态都是304，猜测服务端做了缓存判断，不清楚是不是和这个有关

![image](https://cloud.githubusercontent.com/assets/6064962/10630580/1bf31cac-780a-11e5-9237-c62a78b4fe4d.png)

![image](https://cloud.githubusercontent.com/assets/6064962/10630599/3fa179dc-780a-11e5-918b-e4adea221706.png)

**Comment by alsotang** [comment]
这个问题一直存在，是用户名重复的问题，我也很奇怪重复的用户名是怎么通过数据库 unique index 检查的。

之前遇到这种情况，都是删除其中用户。我看看

**Comment by alsotang** [comment]
现在好了，我把老的那个用户删了

**Comment by alsotang** [comment]
头像一致性的话，由于 github 对于同一个用户都是给一段不变的 avatar 地址，所以正常情况下，github 那边更新的话，我们这边就会随着更新。因为 avatar 地址不会随着用户更新而改变。

**Comment by luoyjx** [comment]
我之前时不时变回原来的头像。。。然后过一阵又变回来

**Comment by alsotang** [comment]
呃。。如果有稳定的可重现场景就好了。。

2015-10-21 16:15 GMT+08:00 yanjixiong <notifications@github.com>:

**Comment by luoyjx** [comment]
这个还好啦，地址都是github那边的，所以我怀疑是他的哪个节点缓存没更新了

**Comment by luoyjx** [comment]
![image](https://cloud.githubusercontent.com/assets/4217102/10746553/12a91ec2-7c87-11e5-8c0a-06f809d642a8.png)
又出现了。。。

**Comment by alsotang** [comment]
你倒是发个链接出来啊

2015-10-27 8:45 GMT+08:00 yanjixiong <notifications@github.com>:

**Comment by luoyjx** [comment]
https://avatars.githubusercontent.com/u/4217102?v=3&s=120
地址确实是github这边的
