### ISSUE TITLE
有针对管理员的管理功能吗

### ISSUE THREAD

**Issue by tianzhihen** [cnodejs/nodeclub#571]
如果管理员不会看数据库怎么办？现在有管理员删帖的功能吗？怎么能成为管理员呢？

**Comment by alsotang** [comment]
呃。。目前没有管理员后台。

但管理员进入帖子里面是可以删帖的。



2015-10-28 14:13 GMT+08:00 tianzhihen <notifications@github.com>:

**Comment by tianzhihen** [comment]
怎么能成为管理员呢？

**Comment by tianzhihen** [comment]
怎么能成为管理员呢？

**Comment by alsotang** [comment]
config.js 里面可以设置

2015-10-28 15:57 GMT+08:00 tianzhihen <notifications@github.com>:

**Comment by tianzhihen** [comment]
感谢 唐少
