### ISSUE TITLE
图片大于1m的时候提示信息修改

### ISSUE THREAD

**Issue by i5ting** [cnodejs/nodeclub#633]
<img width="561" alt="screen shot 2015-11-27 at 10 29 44 am" src="https://cloud.githubusercontent.com/assets/3118295/11432907/cdca8f9c-94f1-11e5-9493-6dd7154e162f.png">

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/11439425/432a92f2-9536-11e5-9491-b327cad3c424.png)
