### ISSUE TITLE
怎么才能加入你们的github 组织

### ISSUE THREAD

**Issue by CoderBOBO** [cnodejs/nodeclub#769]

**Comment by alsotang** [comment]
没有明确的加入方式啊。。。多在社区活跃就好了

2016-02-24 17:56 GMT+08:00 BOBO <notifications@github.com>:

**Comment by CoderBOBO** [comment]
@alsotang 我想加入你们的组织，最近在翻译linux的英文文档还有angular的英文文章，初步接触nodejs希望能加入

**Comment by luoyjx** [comment]
@CoderBOBO 去社区注册个号，没事儿发点干货，提下问就好啦
