### ISSUE TITLE
API需求添加请求（2项）

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#772]
1.  网站端，话题可以查看对某一个回复的回复列表（评论线索图）。目前API中创建回复包含 reply_id 参数，但是并没有提供查询的接口，是否可以补充？

2. 用户个人数据结构中包含两个列表数据分别是：recent_topics 和 recent_replies ，目前这两个数据的最大值都是 5，这个值可否稍微调大一点（10或者20，这个程度应该不会影响性能）。调整原因是数据太少，列表无法填充满页面，数据多一点的话界面上会好看一些。

**Comment by alsotang** [comment]
1. 网页端的这个查看对话功能，是个纯前端的功能，我之前在 api 中，忘记暴露 `reply_id` 这个字段了。通过 `reply_id` 字段，则可以知道某条评论对应的上一条是什么。

api 中我已经加上。

2. 调整到了15，如需更大我可以继续调整上去。
