### ISSUE TITLE
建议判断下浏览器给主页文章列表的标题标签加一个_blank

### ISSUE THREAD

**Issue by zkassing** [cnodejs/nodeclub#776]
因为电脑党更习惯点击在新建标签页打开，而手机党更喜欢当前页面打开，每次电脑浏览社区的时候总是打开一个文章看完顺手就关了，很不方便。手机端可以当前窗口打开右滑返回上一页更方便

**Comment by alsotang** [comment]
不好意思之前在微博回复了这里没有回。

是否新开标签交给用户自己选择
