### ISSUE TITLE
make build 过不去，求大神指导，Error: Duplicate target: /public/editor.min.js

### ISSUE THREAD

**Issue by lijingmt** [cnodejs/nodeclub#782]
debug改false后，运行不了，提示需要make build，但出错。

debug=true是正常运行。。。

求大神指点。

**Comment by JacksonTian** [comment]
额 应该是builder-loader升级导致的。我来修一下吧

**Comment by lijingmt** [comment]
感谢感谢啊，我自己捣鼓了半天。。。对了，你在北京么？我在上海，有机会见见哇

**Comment by alsotang** [comment]
fixed by #784

**Comment by JacksonTian** [comment]
@lijingmt 我在杭州。

**Comment by lijingmt** [comment]
终于过了，不过发送邮件好像还是过不去，163的邮箱可以么？smtp 25端口？

**Comment by lijingmt** [comment]
已经调通了，马上放正式服务器，多谢大神指导，如果有可能，找机会合作一下。
