### ISSUE TITLE
当SESSION失效以后，user的88行，会出一个BUG

### ISSUE THREAD

**Issue by lijingmt** [cnodejs/nodeclub#786]
[root@i-tqp6jc7g nodeclub]# node app
/nodeclub/controllers/user.js:88
    user.error = null;
               ^

TypeError: Cannot set property 'error' of null
  at Query.<anonymous> (nodeclub/controllers/user.js:88:16)
  at nodeclub/node_modules/kareem/index.js:177:19
  at nodeclub/node_modules/kareem/index.js:109:16
  at _combinedTickCallback (node.js:370:9)
  at process._tickCallback (node.js:401:11)

**Comment by lijingmt** [comment]
这个错误重现起来麻烦，我应该是打开一个页面放了一晚上，然后点击设置，就会报这个错误。请大神指点。

**Comment by leizongmin** [comment]
```javascript
/**
 * 需要登录
 */
exports.userRequired = function (req, res, next) {
  if (!req.session || !req.session.user) {
    return res.status(403).send('forbidden!');
  }

  next();
};
```

应该改为：

```javascript
exports.userRequired = function (req, res, next) {
  if (req.session && req.session.user && req.session.user._id) {
    next();
  } else {
    res.status(403).send('forbidden!');
  }
};
```

https://github.com/cnodejs/nodeclub/blob/3ff1a90dd7121c42fc51254874df5af1ad9e5286/middlewares/auth.js#L26

**Comment by lijingmt** [comment]
谢谢，已经好了。

**Comment by alsotang** [comment]
已按照 @leizongmin  的建议修改
