### ISSUE TITLE
增加收藏功能

### ISSUE THREAD

**Issue by alsotang** [cnodejs/nodeclub#795]
https://cnodejs.org/topic/56e79399b5b04c8f6d4ec35e

**Comment by luoyjx** [comment]
哈哈，客户端又得改一波了~

**Comment by alsotang** [comment]
加功能而已。。

**Comment by XGHeaven** [comment]
我也非常同意

**Comment by alsotang** [comment]
@XGHeaven https://cnodejs.org/api 多了 `/topic/collect` 和 `/topic/de_collect` 两个接口。

`/topic/:id` 多了 `is_collect` 参数

**Comment by chenxiaohu** [comment]
个人收藏的帖子列表在哪里啊

**Comment by JacksonTian** [comment]
这个功能不是之前干掉的么？

**Comment by alsotang** [comment]
@chenxiaohu 列表在个人profile页面中
@JacksonTian 又有很多人说要加上，就加了

**Comment by alsotang** [comment]
API 列表更新了一个`主题收藏`章节

**Comment by XGHeaven** [comment]
@alsotang 唐少，似乎收藏列表不支持 limit 和 page 呀

**Comment by alsotang** [comment]
@XGHeaven 考虑到收藏不会太多，所以这个选项就没加了。有必要的话，客户端做做分页就好。

**Comment by XGHeaven** [comment]
@alsotang 我觉得还是有必要的，不管怎样。我先预留着和 get /topics 一样的参数。等什么时候有空了可以加一下 :smile:

**Comment by alsotang** [comment]
嗯嗯，前期你那里就把 page 设为 1，limit 设个很大的数吧

2016-03-16 21:14 GMT+08:00 Xu Tianyang <notifications@github.com>:

**Comment by XGHeaven** [comment]
@alsotang 恩，好的
