### ISSUE TITLE
我的回复列表排序顺序貌似不太对

### ISSUE THREAD

**Issue by i5ting** [cnodejs/nodeclub#805]
https://cnodejs.org/user/i5ting/replies

<img width="1158" alt="screen shot 2016-03-20 at 9 51 50 am" src="https://cloud.githubusercontent.com/assets/3118295/13902405/66bc57b0-ee81-11e5-8778-a2be9c25425d.png">

**Comment by TakWolf** [comment]
这个问题我也发现了

**Comment by XGHeaven** [comment]
我发现 api 也不是很正确。https://github.com/cnodejs/nodeclub/blob/master/api%2Fv1%2Fuser.js#L19

目测 bug 是这里https://github.com/cnodejs/nodeclub/blob/master/controllers%2Fuser.js#L305

**Comment by alsotang** [comment]
@XGHeaven 并不是你指出的那里。

是这样的。我们从回复列表中取出了某个用户最近回复的话题后，用这些 recent_reply_topic_ids 去 topic 表取出topic的标题来。本来这些 recent_reply_topic_ids 是按回复顺序排列的，但是这个列表丢给 mongodb 查询之后，出来的结果并不会严格按照传入的这些 ids 的顺序来，而是会按照 topic 本身的 _id 属性来排。

所以在 recent_reply_topic 数据取出后，需要按照 recent_reply_topic_ids 手动排个序。

----


目前页面和 api 都已经 fix 这个 bug 了。

**Comment by alsotang** [comment]
@XGHeaven 你指出的那个地方确实也算错误，但是那个 order by created 去除之后，取出的数据的排序仍然是需要手动排一次的。

前两天做那个收藏列表的页面时，我刚好遇到了类似的问题。没想到【最近回复】这边一直藏着这个坑。

**Comment by XGHeaven** [comment]
@alsotang 我对nodeclub具体的也不太清楚，但是我印象中，mongodb不是有联合查询么？不可以用么？

**Comment by alsotang** [comment]
我们这个应用创建的时候，mongoose 用得还没那么熟练。。这是个 2011 左右创建的项目了。。
后来重构也没动这一块。

2016-03-21 11:41 GMT+08:00 Xu Tianyang <notifications@github.com>:

**Comment by i5ting** [comment]
@alsotang http://nodeonly.com/nodesang/#/4/14   

《SQL to Aggregation Mapping Chart》
http://docs.mongodb.org/manual/reference/sql-aggregation-comparison/

这个应该比较好理解
