### ISSUE TITLE
API调整建议，关于请求返回格式

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#819]
目前API请求格式不太统一，举例说明：

1.
主题首页：/api/v1/topics
成功返回 200：
{
    “data”:  [
         // 这里是话题列表
    ]
} 

2.
单个话题：/api/v1/topic/5433d5e4e737cbe96dcef312
成功返回 200：
{
    “data”:  {
         // 这里是话题数据
    }
}
错位id返回 422（不知道为啥是422-语义错误，感觉应该为404比较合理）：
{
    "error_msg":"not valid topic id"
}

3.
用户数据： /api/v1/topic_collect/alsotang
成功返回 200：
{
    “data”:  {
         // 这里是用户数据
    }
}
错误 loginname 返回200（这里状态码有问题）：
{
    "error_msg": "user `alsotang2` is not exists"
}

4.其他情况的返回值：
大概为这种模式：
{
    success: true, 
    reply_id: '5433d5e4e737cbe96dcef312'  // 这里的字段是不同接口需要的关键信息
}

{ 
    "success": true, 
    "action": "down"
}

**Comment by TakWolf** [comment]
目前存在的问题：
客户端需要明确知道调用接口是否成功，如果成功，则根据类型解析数据，如果失败，则提示错误。
现在接口中 http状态码 有点问题，并且返回值中不是一定包含 success，所以现在没有办法统一的做错误处理。
目前的做法是暴力法，即解析data数据异常，或者获取关键字段为空，则认为调用失败。

改进建议：统一添加 success 字段，客户端忽略状态吗

之后的格式为：
{
    success: true,
    data [ loginname ] : xx
}

**Comment by alsotang** [comment]
@XGHeaven 有时间帮忙处理一下这个吗？

**Comment by alsotang** [comment]
我的想法跟你一样，我们忽略状态码吧。

成功的话就 success: true。

失败的话，就 success: false, 如果可能，再带上 error_msg

**Comment by alsotang** [comment]
我来处理一下

**Comment by alsotang** [comment]
目前所有 api 接口都会返回 success 字段。目前只有两种状态，true or false。

你看这样如何？

**Comment by XGHeaven** [comment]
要不我们采用 unix 的错误格式可以么？用一个 `code` 或者 `stauts` 字段，返回值为 0 标识正常状态，返回值为非 0 为对应的错误代码，就跟微信那个样子。不过感觉这样代码复杂了好多 😂

**Comment by alsotang** [comment]
两种状态其实够用的。。。我们这种不严肃的场景，只要是 success:false 就直接干掉就好了。



在 2016年4月13日 下午8:29，Xu Tianyang <notifications@github.com>写道：

**Comment by XGHeaven** [comment]
@alsotang 抱歉，最近几天比较忙，我看看今晚有没有空，可以帮忙添加一些东西。

`不严肃的场景` 😂 cnode可是一个大社区

那就 `success:false` 配合上 error_msg 应该就够了

**Comment by alsotang** [comment]
这个 issue 的东西我已经弄完了。。你加新东西的时候，最好微信跟我聊两句，免得到时候我觉得你做了70%，我又没有精力去完善剩下的30%。。。。

2016-04-13 20:33 GMT+08:00 Xu Tianyang <notifications@github.com>:

**Comment by TakWolf** [comment]
@alsotang  已测，没问题

@XGHeaven 不建议在增加复杂类型，http已经有状态码了，再弄一套新的属于冗余

**Comment by alsotang** [comment]
http状态码我个人感觉是有点鸡肋的。。。

成功和错误两种状态是个大的区分。而成功一般就没什么好细分的了。错误的状态，如果要继续细分的话，感觉通过 errorcode
的形式来做区分很局限，总不能每个错误都起个新的状态码，这样状态码一多也不方便复用。

我觉得通过 success: false 加 错误信息 的方式还算是信息的，对于我们的场景来说。

当然，错误信息这东西，如果是人来看的话，这样是足够的。如果是机器使用的话，那么最好是通过 errorcode
的形式来表达，否则总不能让客户端去匹配文案嘛。

还是具体场景具体分析啊。。。。

2016-04-13 22:59 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by XGHeaven** [comment]
@alsotang 好的

我觉得http状态码的好处就是可以将逻辑上的成功处理和实际上的相结合。也就说如果可以直接通过then和catch来判断成功失败，不需要在then里面再判断一次成功失败了。

**Comment by alsotang** [comment]
你这个比喻确实很好啊。promise 也是大致去区分个 then 和 catch 而已。

2016-04-13 23:29 GMT+08:00 Xu Tianyang <notifications@github.com>:

**Comment by TakWolf** [comment]
@alsotang  有些情况下，http状态码还是有意义的，至少百位还是要做区分的。比如：
2xx，客户端解析body一定没问题；其他状态我直接构建错误。

否则的话，你要先去解析一下body，这里存在成功或者失败，成功的话再去解析data，逻辑上麻烦了很多。

我们的场景确实比较简单，没那么复杂，有个success足够了。

**Comment by TakWolf** [comment]
https://github.com/cnodejs/nodeclub/pull/822/files

把http状态码修复了。
另外把 error_msg 全部改成中文了，这样前段调用出现 sucess=false，就直接提示error_msg
