### ISSUE TITLE
API关于主题收藏

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#820]
get /topic_collect/:loginname 用户所收藏的主题

这个接口是不带分页的对吗？返回的数据是所有的收藏数据还是一部分的数据？

如果是部分数据，还是倾向于最早的设计，吧/topic_collect/:loginname接口集成到用户数据中，这样可以避免访问两次网络，而收藏动作改成：
post /topic/:id/collect 收藏主题
post /topic/:id/de_collect 取消主题

另外，缺少一个接口查询一个话题是否收藏（这个目前也可以通过直接获取整个topic对象来查询，但是存在不需要获取整个的情况）

**Comment by alsotang** [comment]
是最近20（具体数字忘了）条收藏数据。

这些地方我觉得。。。改不改都好吧。。

> 缺少一个接口查询一个话题是否收藏

展示是否收藏的地方，不都要去获取一次文章的吗？

**Comment by alsotang** [comment]
我总结一下，一共如下问题：

一、/topic_collect/:loginname 这个接口是否不带分页？

对的，不带。这个接口会返回最新的100条收藏信息。

二、

```
post /topic/:id/collect 收藏主题
post /topic/:id/de_collect 取消主题`
```

我承认这个写法确实更优雅并且更符合 restful，下次设计接口的时候我注意一下这个问题。这回我不想改了。

三、缺少一个接口查询一个话题是否收藏

这个就用 topic 的接口来查就好了。虽然有冗余数据，不过能不加新接口就不加了，免得增加开发复杂度。数据传输这码事儿，总不能指哪打哪的。

**Comment by TakWolf** [comment]
OK
