### ISSUE TITLE
图片带链接时，去掉放大功能

### ISSUE THREAD

**Issue by alsotang** [cnodejs/nodeclub#823]
https://cnodejs.org/topic/570907402a1f230a25be8aab

@XGHeaven 帮忙看看这个。你点击一下帖子中的腾讯云 logo 就能重现了：链接跳了出去，然而图片也放大了。

**Comment by alsotang** [comment]
`[![](https://dn-cnode.qbox.me/FsvQEUQ9vjOy_6NohcGGt3GfTC8v)](http://www.qcloud.com/)`

那个地方的图片写法是这样的。

**Comment by alsotang** [comment]
fixed by #e56c6a34f321fc85f1765b42a8c1f63f27208221

**Comment by XGHeaven** [comment]
OK，我看到了

**Comment by alsotang** [comment]
我搞定了。。。

2016-04-14 22:08 GMT+08:00 Xu Tianyang <notifications@github.com>:
