### ISSUE TITLE
API问题： /messages 接口数据结构缺少create_at字段

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#827]
通知的结构是这样的：
![image](https://cloud.githubusercontent.com/assets/6064962/14571308/18d06eb0-037b-11e6-98dc-fca0510bbe76.png)

通知需要显示时间，之前用的是 message.reply.create_at 字段算作 message 的创建时间，但是似乎还存在下面这种结构：

![image](https://cloud.githubusercontent.com/assets/6064962/14571327/2d9bf09e-037b-11e6-83a7-ff1ab2e0171f.png)

这种通知的方式产生的原因是在主题正文 at 某人，这时message中没有reply对象。（这个貌似是历史遗留问题，最新的代码好像不会再产生这种通知了？）

所以，考虑了一下还是觉得将message的create_at字段暴露出来比较好。
添加字段，不会产生兼容问题。

https://github.com/cnodejs/nodeclub/pull/828

**Comment by alsotang** [comment]
嗯嗯，非敏感字段，可以暴露。

fixed by #828
