### ISSUE TITLE
关于API参数错误状态码422

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#830]
之前API参数错误的状态码写成了422，原因是参考了之前的写法，而且论坛部分参数错误状态也是422。

之后去研究了一下，发现貌似400更合适。400和422含义上是同构的，都有参数错误，无法理解语义的意思。但是400被定义在基本http协议中，而422被定义在RFC 4918 WebDAV中。

stackoverflow上的一个比较详细的讨论：
http://stackoverflow.com/questions/16133923/400-vs-422-response-to-post-of-data

貌似这个问题讨论的还是比较激烈的。
但是综合来看，在我们的情况下，使用400似乎更加合适。

https://github.com/cnodejs/nodeclub/pull/829

**Comment by alsotang** [comment]
fixed by #829

**Comment by alsotang** [comment]
最近几个 pr 都部署好了。我发现我周末竟然没开电脑。。。

在 2016年4月16日 上午4:08，TakWolf <notifications@github.com>写道：
