### ISSUE TITLE
界面上的一些显示问题

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#831]
这个帖子：
https://cnodejs.org/topic/5637549fd426a1404cbd0614

看三楼：环境是macbookpro-chrome
![image](https://cloud.githubusercontent.com/assets/6064962/14606720/fce30b9e-05b0-11e6-96b4-0545da26e107.png)

**Comment by TakWolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6064962/14606772/3a6ffc92-05b1-11e6-93e6-4ca737af2151.png)

收藏按钮是压在线上的，有点略不爽啊

**Comment by TakWolf** [comment]
我这个人患有有强迫癌，请不要打死我。。。

**Comment by TakWolf** [comment]
这两个问题还是忽略吧。。。

**Comment by alsotang** [comment]
在我这里，收藏按钮不是压着的。

但是那个时间的换行问题我也发现了，可关键是换个浏览器这问题就会消失。不懂怎么说这个问题。。。你试着用 inspector
调一下这个换行的问题就会发现神奇了，根本找不到哪句 css 写错了。

2016-04-18 22:10 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by XGHeaven** [comment]
@alsotang 按钮的问题我看了一下，我这里也是压着的，不过可以尝试将 `line-height` 改成 1，可以好看一些。不知道可以么
![image](https://cloud.githubusercontent.com/assets/9291212/14628181/47a7d718-062e-11e6-8ce0-f6d463136d3a.png)

还有那个换行的问题，确实很神奇。目测是字体的问题。
有下面几个解决方案：
1. 把 .user_info 的 display 从 inline-block 改成 inline
2. 给 .reply_time 添加一个 white-space: nowrap
3. 给 .reply_author 的加粗去掉
4. 将 https://github.com/cnodejs/nodeclub/blob/master/views/reply/reply.html#L12 这里的 </a> 从新的一行移到上一行去

我建议同时使用 1 和 4 看看
至于具体是什么原因，我也无法理解，似乎是这个名字有毒。只要是前缀是 `fl` 或者 `fi` 都会出现这样的问题，无法理解。感觉是字体的问题，我把字体从 helvetica neve 切换到 helvetica 就完全没有问题了， 目测是 chrome 对这个字体解析时候出现了问题

**Comment by alsotang** [comment]
压线问题我已经解决了。

那个神奇的换行问题先忽略吧。。太不常见了。我感觉是浏览器 bug

**Comment by XGHeaven** [comment]
我也这么觉得，应该是浏览器的问题。似乎就那一个人有问题。

**Comment by alsotang** [comment]
真是个神奇的css问题。

2016-04-19 18:02 GMT+08:00 TakWolf <notifications@github.com>:
