### ISSUE TITLE
我自己的话题收藏数据显示不正确

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#832]
看图：
![image](https://cloud.githubusercontent.com/assets/6064962/14637918/1fb77e3c-0667-11e6-9e6e-ab70f524620d.png)

![image](https://cloud.githubusercontent.com/assets/6064962/14637945/4d72421c-0667-11e6-8543-6bca4f8065cc.png)

![image](https://cloud.githubusercontent.com/assets/6064962/14637925/2ae8fdda-0667-11e6-9025-a226a9e28ac4.png)

**Comment by TakWolf** [comment]
感觉计算方式有问题，删除的收藏帖子貌似也计算了。

我很早之前测试的时候，收藏过自己的帖子，然后没取消收藏就删除了。

**Comment by TakWolf** [comment]
看来一下实现，这个 user.collect_topic_count 这个是个模型字段，不是算出来的。。。

**Comment by XGHeaven** [comment]
@TakWolf 而且如果一直发删除收藏的api，那么这个数据将会一直减少

**Comment by TakWolf** [comment]
@XGHeaven 
正常情况下删除帖子，收藏数目减少应该是对的啊
我不清楚为啥我的变成负数了

**Comment by XGHeaven** [comment]
我的意思是不正常的情况，比如你不小心点了两次取消收藏，于是确实是取消收藏了，但是也减少了两次。

**Comment by alsotang** [comment]
哈哈，这个地方确实有问题，是这样的。mongodb 不像 mysql 一样连表操作那么方便，`user. collect_topic_count` 其实算是一个冗余的字段，它的值是可以通过 Topic 那张表推算出来的。

实际操作中，我们这边每次调用收藏接口都会把这个数值减1，可能因为你是开发人员，调试接口比较多，很多行为没有跟正常的行为对上，导致出现了这个数据错误。我明天修正一下所有人的。

**Comment by TakWolf** [comment]
@alsotang  我靠，还没睡。。

所以说，像 @XGHeaven 说的这种情况是存在的对吗？API这里感觉应该判断一下

**Comment by XGHeaven** [comment]
其实我也没睡 😂 
因为代码里似乎没有判断
https://github.com/cnodejs/nodeclub/blob/master/api%2Fv1%2Ftopic_collect.js#L123
取消收藏的时候，似乎并没有判断他有没有收藏过

不过现在我要睡了，晚安。刚刚写了一个同步 cocoapods 索引库的玩意

**Comment by alsotang** [comment]
目前存在两个问题要修复。

1. 收藏和取消收藏时，都没有判断类似收藏是否存在。导致错误逻辑一直往下走。
2. TopicCollectSchema 可以加唯一索引。



在 2016年4月20日 上午2:10，Xu Tianyang <notifications@github.com>写道：

**Comment by alsotang** [comment]
旧数据里面，我没有全量修复，只修了 takwolf 你的。。
不过我现在已经阻止重复收藏和重复取消收藏的操作了。

**Comment by alsotang** [comment]
所有用户和帖子的数据都修复了。

https://github.com/cnodejs/nodeclub/commit/b692e514a0340071c0c45756b27dd6199f589efb

**Comment by alsotang** [comment]
数据仍然会有一点对不上的，比如takwolf在数据库中有35个收藏，而其中某个帖子被删除了，所以页面中只显示了34个。

**Comment by TakWolf** [comment]
@alsotang 是的，我现在吧所有的收藏帖子都取消了，数目还有2个

数目这个问题不是很重要，修不修复无所谓。

代码逻辑上修复了判断就OK!

**Comment by alsotang** [comment]
嗯嗯。。这个收藏数目，大概能匹配上就好了。

2016-04-21 3:00 GMT+08:00 TakWolf <notifications@github.com>:
