### ISSUE TITLE
运行了几次，程序有100多M了，这个正常吗，顺带问一下新手入门那里的toptip在哪里改

### ISSUE THREAD

**Issue by NetLogoclub** [cnodejs/nodeclub#833]
运行了几次，程序有100多M了，这个正常吗，顺带问一下新手入门那里的toptip在哪里改

**Comment by NetLogoclub** [comment]
再提个问题，端口可以改为80的吗，我改了没用，要是改，怎么改呢？

**Comment by TakWolf** [comment]
我的整个目录算上 node_modules 一共也是100多M

新手入门在：views/static/getstart.html


该端口在 config.js 中找到这句：
![image](https://cloud.githubusercontent.com/assets/6064962/14712576/450b3ea8-0810-11e6-97b8-c1b53994e230.png)

**Comment by NetLogoclub** [comment]
![image](https://cloud.githubusercontent.com/assets/18526620/14734641/652ddff4-089e-11e6-913f-1f236e6183d8.png)
我后面的toptip已经改了，可是前面的没找到啊，在getstart.html里还是没找到@TakWolf

**Comment by TakWolf** [comment]
好像是我理解有问题，你要找的是哪个topicid?

**Comment by NetLogoclub** [comment]
![image](https://cloud.githubusercontent.com/assets/18526620/14735186/185d0cdc-08a2-11e6-8ec0-307003a91542.png)
其他的top是这样的，就新手入门那个有点特殊，像我上面截图一样

**Comment by TakWolf** [comment]
controllers/static.js

找的这句：

![image](https://cloud.githubusercontent.com/assets/6064962/14735328/f0b11858-08a2-11e6-85c2-9c9678687862.png)


PS：我把 topid 看成 topicid 了

**Comment by NetLogoclub** [comment]
谢谢这么耐心的解答！！！64个赞！！！
