### ISSUE TITLE
七牛上传成功了，但是网站查看不了，原谅小白

### ISSUE THREAD

**Issue by NetLogoclub** [cnodejs/nodeclub#835]
![1](https://cloud.githubusercontent.com/assets/18526620/14765314/4ff56a72-0a0f-11e6-984c-c01f37ebcb75.png)
![2](https://cloud.githubusercontent.com/assets/18526620/14765315/5355ae70-0a0f-11e6-82aa-fb72c1ffa743.png)
![3](https://cloud.githubusercontent.com/assets/18526620/14765316/55ae92c2-0a0f-11e6-9a90-e59510fb7443.png)

**Comment by NetLogoclub** [comment]
谢谢大神 @

**Comment by NetLogoclub** [comment]
还有个问题，网站管理员账号怎么设置啊？也没找到 @alsotang

**Comment by XGHeaven** [comment]
在 config.js 里面有一个叫做 admins 的字段。改一下就好了

**Comment by NetLogoclub** [comment]
@XGHeaven 那不要密码吗?

**Comment by XGHeaven** [comment]
不需要的。因为已经在服务器端写死了

NetLogoclub <notifications@github.com>于2016年4月24日周日 18:04写道：

**Comment by NetLogoclub** [comment]
那怎么管理呢？

**Comment by NetLogoclub** [comment]
还有图片不显示你知道怎么解决吗？七牛存储空间是有图片了，但是网站里不显示 @XGHeaven

**Comment by XGHeaven** [comment]
很平时一样，只不过会多出来加精，置顶等操作方式

NetLogoclub <notifications@github.com>于2016年4月24日周日 19:03写道：

**Comment by liygheart** [comment]
@NetLogoclub 你七牛里是不是设置了防盗图过滤域名了？

**Comment by NetLogoclub** [comment]
没有，刚刚看了一下

**Comment by NetLogoclub** [comment]
@XGHeaven  我用config.js 中写的admins 注册了一个账号，没发现有加精和置顶的功能啊？还有图片不显示你知道怎么解决吗？谢谢！

**Comment by XGHeaven** [comment]
加精和置顶是有的。你仔细找找。
图片的问题，你看看生成的URL和你七牛上面的是否正确？

**Comment by NetLogoclub** [comment]
七牛上是有url，网页源码看看没找到，只有个alt

**Comment by XGHeaven** [comment]
那在提交图片之前，图片是有的对么？也就是在图片上传之后，在输入框有正确的图片markdown输入格式对么？

NetLogoclub <notifications@github.com>于2016年4月25日周一 下午6:21写道：

**Comment by NetLogoclub** [comment]
![Uploading git.png…]()

**Comment by NetLogoclub** [comment]
![git](https://cloud.githubusercontent.com/assets/18526620/14785100/91fc3046-0b2b-11e6-9621-5df1d43892fb.png)
上传之前是这样的格式，我觉得应该是对的

**Comment by XGHeaven** [comment]
。。。好吧，你有没有看 config.js 他 origin 的格式？？他要求是 http://domain.com 而不是 domain.com，
你去改一下试试

NetLogoclub <notifications@github.com>于2016年4月25日周一 下午9:21写道：

**Comment by NetLogoclub** [comment]
哇，大神，膜拜膜拜，64个谢谢！我没注意到要http://，基础太差

**Comment by XGHeaven** [comment]
恩，那就可以 close 了

NetLogoclub <notifications@github.com>于2016年4月25日周一 下午9:52写道：

**Comment by NetLogoclub** [comment]
我能贪心的说一下，没找到管理员权限吗？我配置了个用户名，然后填写那个用户名去注册，就能成为管理员吗？那要是别人恰好用了这个用户名，那不是管理员权限就给他注册走了？我的也没有加精和置顶功能，又要麻烦大神您了！

**Comment by XGHeaven** [comment]
是的。所以肯定要在注册完成之后，将用户设置为管理员。你配置文件是什么样子的？

**Comment by NetLogoclub** [comment]
![image](https://cloud.githubusercontent.com/assets/18526620/14803266/aaea5cb8-0b8a-11e6-9b07-71e738ef0233.png)
就是改了一个登陆名

**Comment by XGHeaven** [comment]
不是这样的，就那我的登录名字举个例子。
// 一猜我就知道你这里肯定写错了，在说上面都写的很清楚了。。。
```
admins: {
    xgheaven: true
}
```
至于为什么这样做，可能是方便以后暂时修改用户的管理权，或者是站长当初写的时候故意的 😓

**Comment by NetLogoclub** [comment]
好吧，谢谢大神大人，我太开心了，终于一个个 问题都解决了，再次表示感谢！

**Comment by alsotang** [comment]
示例配置文件也没法事无巨细地写，还是要多调试啊

2016-04-26 9:23 GMT+08:00 NetLogoclub <notifications@github.com>:

**Comment by NetLogoclub** [comment]
已经很感谢大神了

**Comment by tianshaokai** [comment]
我的图片已经出来了，可是上传的图片没有文件名，文件名都是七牛自动生成的

**Comment by NetLogoclub** [comment]
你把七牛的文件名改了，然后网页里的文件名也改一下试试，我没试过哦 不过图片在网页里干嘛要名字呢？

**Comment by tianshaokai** [comment]
链接里没有名字 就看不出来图片是 jpg 还是 png gif 图片，下载下来的时候 也没有文件名称 @alsotang  这是怎么设置文件名称呢

**Comment by NetLogoclub** [comment]
网页里只是引用了七牛图片的外链地址 你要上传以后命名的话 你需要更改上传后七牛上的图片的外链地址 然后和你网页地址对应起来。你可以自己先在七牛上传一个图片，自己命名的，然后你到网页里去引用 下载的话就可以看到你的命名和格式了

**Comment by tianshaokai** [comment]
@NetLogoclub  我的意思是上传的时候就定义好名字

**Comment by XGHeaven** [comment]
@tianshaokai 会有后缀名的

**Comment by tianshaokai** [comment]
我搭建的站点上传后没有设置啊，七牛云里也没有，我配置的有问题了吗
