### ISSUE TITLE
windows下使用问题

### ISSUE THREAD

**Issue by mlyknown** [cnodejs/nodeclub#837]
![qq 20160428235844](https://cloud.githubusercontent.com/assets/12880984/14892405/3cbf4004-0d9d-11e6-8992-87055a6e5ca1.png)

windows下报错，首页不能访问

**Comment by XGHeaven** [comment]
为什么会访问 /admin，这个是不存在的。至少在我本地是这样的

mlyknown <notifications@github.com>于2016年4月29日周五 上午12:00写道：

**Comment by mlyknown** [comment]
这个号了，我换下redis的版本，就ok了 0.0
