### ISSUE TITLE
Github上的邮箱修改了，然后用Github重新登录cnodejs.org邮箱还是老的邮箱

### ISSUE THREAD

**Issue by liygheart** [cnodejs/nodeclub#838]

**Comment by alsotang** [comment]
是的，邮箱一旦填入就固定了

2016-04-29 16:21 GMT+08:00 朋也 <notifications@github.com>:

**Comment by liygheart** [comment]
这个，，，不是bug?
或者可以麻烦大大给手动改下邮箱么?

**Comment by XGHeaven** [comment]
// 话说这个邮箱不是应该在设置里能更改的么

朋也 <notifications@github.com>于2016年4月29日周五 下午4:41写道：

**Comment by liygheart** [comment]
改不了，我试过了
2016年4月29日 22:39，"Xu Tianyang" <notifications@github.com>写道：

**Comment by alsotang** [comment]
你的id是多少？我帮你改改吧

2016-04-30 0:01 GMT+08:00 朋也 <notifications@github.com>:

**Comment by liygheart** [comment]
liygheart
现在的邮箱是py2qiuse@gmail.com
谢谢大大
2016年4月30日 00:22，"alsotang" <notifications@github.com>写道：

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/14935021/a2dff4ce-0ef5-11e6-8f68-bef30c9d5543.png)

这样可以了吧？

**Comment by liygheart** [comment]
恩恩，感谢大大
