### ISSUE TITLE
MongoDB 是 v2.6，Redis 是 v2.8.9 必须安装这个版本吗

### ISSUE THREAD

**Issue by tianshaokai** [cnodejs/nodeclub#839]
MongoDB 是 v2.6，Redis 是 v2.8.9 可以安装新版本的吗 还有Nodejs 可以安装新版本吗

**Comment by tianshaokai** [comment]
@alsotang 安装新版本没事吧，可以兼容吗

**Comment by TakWolf** [comment]
mongodb和redis可以更新到最新版本，亲测没问题
node版本请保持在v4或者v5

**Comment by alsotang** [comment]
我更新了一下，现在：线上跑的是 Node.js v4.4.0，MongoDB 是 v3.0.5，Redis 是 v3.0.3。

对了，最近node6刚出，还是用5或者4吧

2016-04-30 11:14 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by XGHeaven** [comment]
v6 我测试的时候，是有问题的。不建议使用

**Comment by alsotang** [comment]
v6 我专门开了一个 issue： https://github.com/cnodejs/nodeclub/issues/840

v6 的测试可以看这里：https://travis-ci.org/cnodejs/nodeclub

2016-04-30 17:35 GMT+08:00 Xu Tianyang <notifications@github.com>:
