### ISSUE TITLE
关于XSS过滤的一些疑问

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#844]
这块我不是特别的清楚，姑且还是问一下：

XSS的基本原理我大概有个概念，因为markdown默认支持html标签，所以这里的数据通常要进行过滤。

nodeclub中过滤的时机是发生在渲染的时候吗？还是在提交markdown的时候过滤之后存入数据库。

如果是前者，在API调用的时候，如果mdrender = false，返回的markdown源码是过滤过的还是没过滤过的？

**Comment by liygheart** [comment]
Markdown可以设置不解析html代码

TakWolf <notifications@github.com>于2016年5月10日周二 15:27写道：

**Comment by alsotang** [comment]
我们是直接把用户提交的 markdown 原始数据存入数据库，在展示的时候进行 一、markdown 渲染 二、xss过滤。

如果 mdrender = true，那么我们服务端会进行渲染 + 过滤。如果 false 的话，那么既然渲染都交出去了，我们服务端也没法进行 xss
过滤。因为 xss 过滤要求输入的是 html 结构的字符串。

在 2016年5月10日 下午3:36，朋也 <notifications@github.com>写道：
