### ISSUE TITLE
线上GitHub登录回调地址配置问题

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#845]
https://github.com/login/oauth/authorize?response_type=code&redirect_uri=http://cnodejs.org/auth/github/callback&client_id=0625d398dd9166a196e9

配置的是http，会被重定向为https，多余一次重定向。

偶然发现的，不是啥大问题

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/15288983/974dc164-1ba1-11e6-961e-ecf9bfa0b606.png)


@fengmk2  帮改改？

**Comment by fengmk2** [comment]
done 

![image](https://cloud.githubusercontent.com/assets/156269/15292766/4411e5b4-1bb7-11e6-9344-1c847e6f7f88.png)

**Comment by TakWolf** [comment]
@alsotang 网站端的配置也要改，callback_url参数必须匹配

**Comment by alsotang** [comment]
网站这边也改了

2016-05-16 22:44 GMT+08:00 TakWolf <notifications@github.com>:
