### ISSUE TITLE
怎么样以管理员的身份登录到系统呀

### ISSUE THREAD

**Issue by mihongkun** [cnodejs/nodeclub#849]
顶置 和 精华 弄不出来

**Comment by liygheart** [comment]
config.default.js 里有配置说明

**Comment by mihongkun** [comment]
@liygheart 正在看... 谢谢

**Comment by mihongkun** [comment]
@liygheart 看得很仔细 只是在web_router发现了一点蛛丝马迹，至于config.default.js并不懂怎么办

**Comment by TakWolf** [comment]
https://github.com/cnodejs/nodeclub/blob/master/config.default.js#L78

修改这里

**Comment by mihongkun** [comment]
@liygheart @TakWolf  我来尝试一下 ，请原谅我粗心没看到

**Comment by tomoya92** [comment]
这个可以关闭了吧？

**Comment by alsotang** [comment]
哈哈 经常关的不及时。。。
