### ISSUE TITLE
已读消息（更新帖子后）变为未读消息

### ISSUE THREAD

**Issue by starduliang** [cnodejs/nodeclub#852]
场景：
我发了一篇帖子，有小伙儿半给我留言，我看到了我有未读消息，
未读消息全点开看过之后（也就是说没有未读消息了），
我重新更新了（加了点东西）我的帖子，
发现未读消息又出现了（是之前已经读过的），
点开未读消息看一下，
不显示有未读消息了。
我的账号starduliang（和当前github账号关联登陆的）

**Comment by TakWolf** [comment]
你的帖子正文中是不是at某人了

正文中存在at，编辑更新之后会再次创建一条通知消息

**Comment by alsotang** [comment]
按理说自己是没法 at 自己的。
但是如果别人更新了它的帖子，帖子中 at 你的话，这时候会有重复通知出现。

我怀疑是回复你的那个小伙伴，在你更新的同时，也更新了他的回复导致的。时间比较巧。

**Comment by starduliang** [comment]
我测一下再，确认后回复

**Comment by starduliang** [comment]
有@   如下：
'npm install npm@3 -g'

但是我刚才稍微加点东西更新一下后没出现之前已读消息全变成未读消息的情况。。。我的幻觉？没事儿我只是提一下。
