### ISSUE TITLE
关于AGPL协议的问题

### ISSUE THREAD

**Issue by jamiesun** [cnodejs/nodeclub#859]
开发者，你好，最近我在了解AGPL协议的一些细节，对于AGPL协议，要求相关的通过网络调用的应用都要采用和其相同的AGPL协议，而nodeclub采用mongodb作为数据存储，开源协议采用MIT，是不是不符合要求。

**Comment by alsotang** [comment]
这个问题我还真搞不清楚。

我们之所以使用 MIT，是因为 MIT 是最宽松的协议，比  AGPL 更宽松。所以这么来说的话，更宽松的协议应该是可以调用稍微严格的协议的吧？

**Comment by alsotang** [comment]
不少公司用着 mongodb 当做商业服务的后端，也没见这方面的新闻出来过。

我们的用法相当常规，感觉应该没有触犯他们的开源协议。

**Comment by TakWolf** [comment]
不冲突
AGPL相当于在GPL协议基础上添加A（A=AFFERO），解决原有GPL协议在不发布软件，但是在云端以服务形式提供则可以不公开源代码这一漏洞，即AGPL下，如果在云端运行，也必须公布源代码。

在GPL协议下，如果项目修改自原项目（包括静态链接），则衍生项目必须继承GPL协议，并且开放源代码。但是，如果以动态链接调用或者服务的形式被第三方使用，则不再GPL的范围之内。

nodeclub是以服务的形式使用mongodb，本身不包含mongodb的源代码，不需要关心GPL

**Comment by jamiesun** [comment]
因为我自己也有采用AGPL协议，给用户带来担忧。所以咨询过资深人士后，我自己的项目决定强行移除AGPL协议。

AGPL确实是非常严格的协议，我觉得nodecloub本身采用MIT没有问题，应该是是使用者需要处理这个问题，

**Comment by jamiesun** [comment]
@TakWolf  还是你的解释比较准确

**Comment by JacksonTian** [comment]
我们哪里涉及到了AGPL吗？

**Comment by alsotang** [comment]
@JacksonTian mongodb 是 agpl
@TakWolf 👍

**Comment by dead-horse** [comment]
mongodb 的没问题，然后其实 pm2 也是 agpl .. 没有混合编译使用源码。
