### ISSUE TITLE
样式问题：footer固定到了底部了吗？页面有遮挡

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#865]
![image](https://cloud.githubusercontent.com/assets/6064962/16580490/58acc9e8-42d7-11e6-8db9-0b049e55c051.png)

按钮挡住了，我已经发不出去回复了。。。

**Comment by alsotang** [comment]
?????

难道跟这个有关？https://github.com/cnodejs/nodeclub/commit/8f52f66f6910d85b38294cd8b2ee8c990432ef4f

不过这几天都没有改任何css和html啊

**Comment by TakWolf** [comment]
@alsotang 之前是这个帖子 https://cnodejs.org/topic/577b7751fb1d649f05fec792  没有回复的时候出现的
我现在看帖子貌似又都正常了。。
