### ISSUE TITLE
关于 Redis 存储 session 的问题

### ISSUE THREAD

**Issue by jamiesun** [cnodejs/nodeclub#867]
nodeclub 中 默认使用 redis 是没有配置密码的，建议把密码配置加进去，在使用必须密码访问的 redis 时，需要额外修改代码才能够运行起来。

**Comment by alsotang** [comment]
修改之后长什么样？能不能提个 pr 过来？

2016-07-17 9:39 GMT+08:00 jamiesun <notifications@github.com>:

**Comment by alsotang** [comment]
我这边对 redis 也没有那么熟悉


在 2016年7月17日 下午5:49，alsotang <alsotang@gmail.com>写道：

**Comment by alsotang** [comment]
https://github.com/cnodejs/nodeclub/commit/4474a93a4fe34a9c6af7d4b311c1d1697c82bdb3

这么修了一下，你看可以吗？

**Comment by tomoya92** [comment]
redis配置文件里有绑定ip的配置，就算没密码，也没事吧！

**Comment by awong1900** [comment]
确实更完善了。 一般我用防火墙禁掉外网访问。

**Comment by alsotang** [comment]
有没有人告诉我，我这样改行不行啊。。。？

2016-07-18 9:40 GMT+08:00 Ten Wong <notifications@github.com>:

**Comment by jamiesun** [comment]
我已经用了，可以
