### ISSUE TITLE
能否清理一下无效的分支？目前跟进代码查看起来不是特别方便

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#876]
比如，现在遗留了大量的 greenkeeper-\* 分支，实际上这些分支合并之后就没啥意义了，现在还保留了很多，非常影响阅读。

其他的一些分支，虽然有一些还没有解决，但是年代也过于久远了，代码结构以及发送很大变化了，基本也无法处理了

自己fork了一份代码，随时会拉取最新进度，但是每次找master要找半天

**Comment by alsotang** [comment]
每次找 master 找半天？啥意思？branch 在 git 里面跟 tag 的意思差不多的。感觉不清理的问题不大

在 2016年8月14日 上午5:24，TakWolf <notifications@github.com>写道：

**Comment by luoyjx** [comment]
不是有搜索嘛....

**Comment by awong1900** [comment]
感觉可以整理下，一些feature branch可以删了。

**Comment by TakWolf** [comment]
我自己的情况，平时git通常是在source tree下，因为观察形状更明了。

经常要从主源拉去master分支，就会出现这个尴尬情况：

![image](https://cloud.githubusercontent.com/assets/6064962/17687250/1a16c45a-63a6-11e6-9ffe-3963f14accfe.png)

生成tag之后，通过不怎么关心，用到才去找

而branch是需要随时拉取的，目前很多分支确实是没用的

**Comment by alsotang** [comment]
........你这个 gui 不能拉取一个 repo 下的所有分支吗？直接全部拉就好了

在 2016年8月16日 上午11:40，TakWolf <notifications@github.com>写道：
