### ISSUE TITLE
用户用邮箱注册，收到激活邮件，是什么 问题？

### ISSUE THREAD

**Issue by randyliu66** [cnodejs/nodeclub#879]
用户用邮箱注册，收到激活邮件，是什么 问题？

**Comment by randyliu66** [comment]
收不到

**Comment by awong1900** [comment]
先搜索下关掉issue是不是有类似的。而且你要描述清楚你的问题，做过什么尝试。
![image](https://cloud.githubusercontent.com/assets/4022612/18158975/1f0ea86e-7059-11e6-9f78-825e650aaf2a.png)

**Comment by TakWolf** [comment]
邮件配置参考：
https://github.com/cnodejs/nodeclub/issues/854

另外，debug=true的时候，不会发送邮件

**Comment by randyliu66** [comment]
set off debug
build all
163 email set authorized code
set password as auth code and change localhost to domain name ,then restart nodeclub.

Working …

灰常感谢！！！
