### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by tomoya92** [cnodejs/nodeclub#880]
有人碰到过吗？safari  往上翻不动了

![f4c5fa6b-95f4-4465-8845-1854a2481145](https://cloud.githubusercontent.com/assets/6915570/18240947/2a7048f4-7381-11e6-9b6a-97f8a18517c9.png)

**Comment by TakWolf** [comment]
https://github.com/cnodejs/nodeclub/issues/865

**Comment by tomoya92** [comment]
呃，发之前偷懒了，没有搜一下😂

**Comment by tomoya92** [comment]
但是这个问题貌似没有被解决呀

**Comment by tomoya92** [comment]
https://cnodejs.org/topic/57cc56fe5f7f910c27696d87  这个话题，刷新时好时坏

**Comment by TakWolf** [comment]
这个问题我之前遇到过几次，但是无法稳定复现
