### ISSUE TITLE
请问怎么进管理后台

### ISSUE THREAD

**Issue by KMPYD** [cnodejs/nodeclub#888]
// admin 可删除话题，编辑标签。把 user_login_name 换成你的登录名
  admins: { user_login_name: true },

注册了一个admin的用户名邮件激活之后登录，不能管理；
请问上面那个代码怎么改：
  // admin 可删除话题，编辑标签。把 user_login_name 换成你的登录名
  admins: { admin },

这样吗

**Comment by KMPYD** [comment]
2.这样改吗
  // admin 可删除话题，编辑标签。把 user_login_name 换成你的登录名
  admins: { user_login_admin: true },

**Comment by TakWolf** [comment]
admins: { KMPYD: true },

这样
