### ISSUE TITLE
npm install NodeClub -g , ERR!

### ISSUE THREAD

**Issue by pangguoming** [cnodejs/nodeclub#897]
楼主看下面错误 CentOS 6.7 的系统
[root@ip-172-31-2-153 node-v4.6.1]# npm install NodeClub -g
npm ERR! Linux 2.6.32-642.6.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v4.6.0/bin/node" "/root/.nvm/versions/node/v4.6.0/bin/npm" "install" "NodeClub" "-g"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/NodeClub
npm ERR! 404 
npm ERR! 404 'NodeClub' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/node-v4.6.1/npm-debug.log
[root@ip-172-31-2-153 node-v4.6.1]#

**Comment by TakWolf** [comment]
你在安装啥呢，nodeclub又不是一个npm包

**Comment by pangguoming** [comment]
额，我今天有点二
