### ISSUE TITLE
github 授权登录出错

### ISSUE THREAD

**Issue by pangguoming** [cnodejs/nodeclub#902]
![image](https://cloud.githubusercontent.com/assets/7269202/19716613/5aade446-9b8f-11e6-834e-91e8bb208a19.png)

**Comment by TakWolf** [comment]
错误已经表明了，需要添加  x-real-ip 头
你是不是nginx代理配置有问题

**Comment by pangguoming** [comment]
我没有用nginx, 直接node 接80端口

**Comment by pangguoming** [comment]
另外邮箱 也无法发信
![image](https://cloud.githubusercontent.com/assets/7269202/19717176/f10f8942-9b91-11e6-9dc9-0e1cb6a9e191.png)

**Comment by TakWolf** [comment]
邮件的所有问题看这个：https://github.com/cnodejs/nodeclub/issues/854

github内个错误出现的条件在详细说明一下

**Comment by pangguoming** [comment]
github 登录的报错上面说了，用的是 AWS Centos 虚拟机 发布的网址http://neo4j.com.cn/
只装了node.js , mongodb, redis, neo4j

**Comment by pangguoming** [comment]
@TakWolf ??

**Comment by TakWolf** [comment]
没遇到过这个问题，感觉上是github配置有问题
这里的配置你贴一下

**Comment by pangguoming** [comment]
@TakWolf 
![image](https://cloud.githubusercontent.com/assets/7269202/19719497/ce92010a-9b9c-11e6-872d-717a6f43b322.png)

**Comment by pangguoming** [comment]
![image](https://cloud.githubusercontent.com/assets/7269202/19719596/3c682d62-9b9d-11e6-98df-5cd46b9a2843.png)

**Comment by pangguoming** [comment]
@alsotang

**Comment by TakWolf** [comment]
不知道了，没遇到过这个错误。
感觉你的配置没有问题。
猜测问题仍然出在代理层上。
Github内部可能要验证客户端ip，如果走了代理，clientIp就变成服务端的了，所有通常用  x-real-ip 记录原始的ip地址。

AWS Centos 虚拟机
这个东西我没用过，不了解。他的网络拓扑是怎么做的？
你检查一下是不是跟这个东西有关系

**Comment by pangguoming** [comment]
@TakWolf  找到原因了，还没有解决办法
代码：nodeclub-master\middlewares\limit.js 最后面 读req.get('x-real-ip') ，返回空了，
![image](https://cloud.githubusercontent.com/assets/7269202/19759077/cdb40f96-9c5d-11e6-896b-cdd9010692cf.png)

因为，在AWS EC2实例中：
http://stackoverflow.com/questions/25722205/x-real-ip-x-forwarded-for-headers-always-null-on-ec2tomcat

，需要改下代码

**Comment by pangguoming** [comment]
@TakWolf 搞定了，
req.get('x-real-ip')换成 req.connection.remoteAddress;
