### ISSUE TITLE
关于使用CNode二次开发的问题

### ISSUE THREAD

**Issue by shaohao2014** [cnodejs/nodeclub#917]
你好，打扰了。

    用了CNode之后，我最大的感受就是快，用ab压力测试，10000个并发的情况下也基本能够轻松应对。这也是我选用CNode的主要原因之一。另外，我决定用CNode并不是用来做社区，而是计划做一个本地分类信息服务网站。与之配套的移动端，我打算用微信小程序来做，再加上CNode使用的是mongodb，原生支持微信小程序对json数据的增删改查。鉴于以上两个方面原因，我决定使用CNode来进行二次开发。
目前遇到两个问题，请给以指点。

问题1：
   关于 CNode网站注册问题，在cnondjs.org里边注册页面，通过github老是注册不成功，没有别的注册方法吗？

问题2：
   关于二次开发的问题。我打算用CNode构建一个分类信息网站，请问你用的什么开发框架开发的cnode？我计划通过cnode的学习并二次开发，从而转到前端全栈开发上面来，毕竟我对这个很有兴趣。
   我目前刚刚转到前端上来，以前偏后端一些，用的是lnmp架构。我有一些ES5、6的基础，对前端底层架构和原理性知识也很有兴趣，另外，对前端整体的开发流程、历史、现状、职业规划只是走马观花的了解了一下，没有系统深入的研究。像我这种情况，直接通过学习cnode源码进行二次开发，会不会学习曲线陡然了一些？想听到你的建议。

   望兄弟在帮忙之中抽出一点时间给予指点，感谢！

**Comment by TakWolf** [comment]
1. github需要设置公开邮件才能注册。

2. nodeclub核心框架是 express + mongoose，使用了eventproxy来解决回调问题，其他的依赖请参考 package.json 
 https://github.com/cnodejs/nodeclub/blob/master/package.json

3.如果你是nodejs新手的话，可以看看nodeclub，代码不是特别复杂
但是推荐看这个教程 https://github.com/nswbmw/N-blog

4.关于二次开发，不太清楚你的分类信息网站的需求，但如果不是论坛的形式，改造nodeclub估计要做不少工作。

**Comment by shaohao2014** [comment]
很感谢！你给出的解答很详细，我受益匪浅帮助很大。辛苦了！

**Comment by alsotang** [comment]
问题1

你自己调试吧。github这个登陆方式对你来说应该可以去掉，cnode本身是有原生登陆方式的，只是 cnode 关掉了。nodeclub 源码里面有。

问题2 

直接学习 cnode 源码还是靠谱的，因为 nodeclub 结构简单，所以不会出现很多因为业务存在的特殊代码
