### ISSUE TITLE
能否提供单独标记未读message为已读的接口？

### ISSUE THREAD

**Issue by P-ppc** [cnodejs/nodeclub#935]

**Comment by alsotang** [comment]
感觉 ` /messages` 这个接口可以加一个 `not_mark` 参数。让它不自动标记已读，有空帮加一下吗？

**Comment by alsotang** [comment]
我来加上吧

**Comment by P-ppc** [comment]
@alsotang  我的意思是提供单独的根据messge的id来标识为已读的接口

**Comment by alsotang** [comment]
哦哦，你说这个啊。怪不得我去看代码的时候，发现api这边，读消息和标记消息的接口是互不影响的。

你想要的这个接口，会改变交互吧。就是用户点击哪条未读，才标记哪条为未读是吧？

不这么弄了，像微博一样，一次也是标记所有未读为已读的。

**Comment by P-ppc** [comment]
新增一个接口实现这功能的话，是不会改变交互的吧

**Comment by Apcan** [comment]
#940 @P-ppc @alsotang

**Comment by Apcan** [comment]
#941 @alsotang 你好上一条提交造成的问题 在这里修复，不好意思造成了问题，实在抱歉

**Comment by alsotang** [comment]
https://github.com/cnodejs/nodeclub/pull/940 已加入
