### ISSUE TITLE
我的收藏列表分页bug

### ISSUE THREAD

**Issue by jiangli373** [cnodejs/nodeclub#944]
https://github.com/cnodejs/nodeclub/blob/master/controllers/user.js#L230
![image](https://cloud.githubusercontent.com/assets/1632862/25035326/7ab3dd8e-211f-11e7-83e4-3f1ec1896c6d.png)

这里算的页数是根据当前页数的条数除以limit得出来的，导致前端显示总是一页

例如https://cnodejs.org/user/JustforNode/collections 这个用户有45个收藏，前端只显示一页

https://cnodejs.org/user/JustforNode/collections?page=2 可以通过这个链接看到第二页的条目

**Comment by alsotang** [comment]
已发布 #945
