### ISSUE TITLE
样式显示问题，markdown中的有序列表 <ol>

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#946]
https://cnodejs.org/topic/58fef3dc31e8c2bb1c3dcdeb#58fefa63bbaf2f3f569be253

![image](https://cloud.githubusercontent.com/assets/6064962/25373552/b8d0b5b4-29cc-11e7-8c41-b08dae80144d.png)

![image](https://cloud.githubusercontent.com/assets/6064962/25373574/d0ab757a-29cc-11e7-9249-43f29e705eb1.png)

![image](https://cloud.githubusercontent.com/assets/6064962/25373591/e5337a92-29cc-11e7-868e-9a81d1b84ae1.png)

环境为 macOS 10.12.4，Chrome  57.0.2987.133 (64-bit)

**Comment by alsotang** [comment]
解析器算是有问题，list之间不要空格就好了

**Comment by TakWolf** [comment]
确实如此
