### ISSUE TITLE
无法发送邮件 github 无法登录

### ISSUE THREAD

**Issue by falost** [cnodejs/nodeclub#948]
无法正常的发送注册邮件，邮件格式是按照提供的配置的

使用github 登录后绑定帐号的时候会出现：频率限制：当前操作每天可以进行 undefined 次

**Comment by TakWolf** [comment]
邮件问题，请看这个：
https://github.com/cnodejs/nodeclub/issues/943#issuecomment-293781574

频率限制，请确认这几个配置正确：
https://github.com/cnodejs/nodeclub/blob/master/config.default.js#L131

**Comment by falost** [comment]
邮件问题解决了，是因为126的邮箱需要客户端的密码来发送
频率限制为默认的设置，就是1000那个，这里没有做改动！

**Comment by TakWolf** [comment]
这句错误提示来源于这里：https://github.com/cnodejs/nodeclub/blob/88f5d9a141eb6b6dbb785ebbd8b79df3b75555eb/middlewares/limit.js

能确定是哪个动作触发了限制吗？

**Comment by falost** [comment]
在使用github登录的时候出现的 
注册和关联帐号的时候 均会出现

**Comment by TakWolf** [comment]
感觉是个Bug

@alsotang

**Comment by falost** [comment]
那就可能是个BUG了啊

**Comment by falost** [comment]
问题已经解决，并不是BUG，是因我用的版本比较老，是16年下载的，失误了，已经更新为最新版本的。感谢你的回答！
