### ISSUE TITLE
线上环境，话题 id = 5992936a4e3c4e5a7021b0bd ，这个数据内容过大，影响性能

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/nodeclub#980]
问题话题为：https://cnodejs.org/topic/5992936a4e3c4e5a7021b0bd

在测试通道中，应该是有人测试图片上传，非外链而是值传 base64，由于图片太大，而导致内容过大。

api接口首页列表结构会返回 content 数据，因此分页第三页加载超级慢，导致超时。

@alsotang 处理一下这个数据吧。

**Comment by alsotang** [comment]
这帖子我删了。

理论上来说，这些大量内容应该是在某个处理过程中拖慢了服务器的速度。比如 md渲染的部分这类的。
光是它的大小来说，下载起来还是很快的。

**Comment by TakWolf** [comment]
@alsotang 确实，参数设置为 render = true 了
