### ISSUE TITLE
如何将MongoDB改为MySQL

### ISSUE THREAD

**Issue by fandasoft** [cnodejs/nodeclub#997]
如果要将MongoDB改为MySQL的话，请问该如何着手？

**Comment by tomoya92** [comment]
你可以试着用一下 sequelizejs 改改

**Comment by fandasoft** [comment]
@tomoya92  谢谢 🙏

再问，MongoDB操作的部分主要集中在哪些文件？到文件里面去找了一下，没有看到有DB操作的地方。

**Comment by tomoya92** [comment]
@fandasoft model controller
